# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yml build --paralell
    - run: docker tag udagram-api-feed presidentbanda/udagram-api-feed:v1
    - run: docker tag udagram-api-user presidentbanda/udagram-api-user:v1
    - run: docker tag udagram-frontend:local presidentbanda/udagram-frontend:v1
    - run: docker tag udagram-reverseproxy presidentbanda/udagram-reverseproxy:v1
    - run: docker push presidentbanda/udagram-api-feed:v1
    - run: docker push presidentbanda/udagram-api-user:v1
    - run: docker push presidentbanda/udagram-frontend:v1
    - run: docker push presidentbanda/udagram-reverseproxy:v1
